events {
    worker_connections 4096;
}

http {
    client_max_body_size 32m;
    
    server {
        listen 443 ssl default_server;
        ssl_certificate /pki/issued/lab-full.crt;
        ssl_certificate_key /pki/private/lab.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://guacamole:8080;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            # The following two lines improve RDP performance over guacamole greatly.
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
            proxy_buffering    off;
            proxy_http_version 1.1;
        }
    }
}
